-- drop server audit
 
USE [master]
GO
IF  EXISTS (SELECT * FROM sys.server_audits 
  WHERE name = N'MSSQL_Server_Audit')
BEGIN
 ALTER SERVER AUDIT MSSQL_Server_Audit WITH (STATE = OFF) 
 DROP SERVER AUDIT [MSSQL_Server_Audit]
END
GO
 
 
-- create server audit
 
CREATE SERVER AUDIT [MSSQL_Server_Audit]
TO FILE 
(	FILEPATH = N'C:\\AUDIT\'
	,MAXSIZE = 200 MB
	,MAX_ROLLOVER_FILES = 5
	,RESERVE_DISK_SPACE = OFF
)
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE
)
ALTER SERVER AUDIT [MSSQL_Server_Audit] WITH (STATE = ON)
GO

-- drop server audit specification
 
USE [master]
GO
 
IF  EXISTS (SELECT * FROM sys.server_audit_specifications 
  WHERE name = N'MSSQL_Server_Specification')
BEGIN
 ALTER SERVER AUDIT SPECIFICATION MSSQL_Server_Specification WITH (STATE = OFF) 
 DROP SERVER AUDIT SPECIFICATION [MSSQL_Server_Specification]
END
GO
 
/*
This section checks for the version of the SQL Server and creates the Server Audit Specification
*/
 
IF (SELECT cast(left(cast(serverproperty('productversion') as varchar), 4) as decimal(5, 3))) < 11 
BEGIN 
	--PRINT 'SQL 2008%'
 
	CREATE SERVER AUDIT SPECIFICATION [MSSQL_Server_Specification]
	FOR SERVER AUDIT [MSSQL_Server_Audit]
	ADD (APPLICATION_ROLE_CHANGE_PASSWORD_GROUP ),
	ADD (AUDIT_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (DATABASE_OWNERSHIP_CHANGE_GROUP),
	ADD (DATABASE_PERMISSION_CHANGE_GROUP ),
	ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),
	ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP ),
	ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
	ADD (LOGIN_CHANGE_PASSWORD_GROUP),
	ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (SERVER_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (SERVER_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (SERVER_PERMISSION_CHANGE_GROUP ),
	ADD (SERVER_PRINCIPAL_CHANGE_GROUP),
	ADD (SERVER_PRINCIPAL_IMPERSONATION_GROUP ),
	ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP)
	WITH (STATE = ON)
	
	END 
 
ELSE 
 
	BEGIN 
 
	CREATE SERVER AUDIT SPECIFICATION [MSSQL_Server_Specification]
	FOR SERVER AUDIT [MSSQL_Server_Audit]
	ADD (APPLICATION_ROLE_CHANGE_PASSWORD_GROUP),
	ADD (AUDIT_CHANGE_GROUP),
	ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP),
	ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP ),
	ADD (DATABASE_OWNERSHIP_CHANGE_GROUP ),
	ADD (DATABASE_PERMISSION_CHANGE_GROUP),
	ADD (DATABASE_PRINCIPAL_CHANGE_GROUP ),
	ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP),
	ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP ),
	ADD (LOGIN_CHANGE_PASSWORD_GROUP ),
	ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP),
	ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP ),
	ADD (SERVER_OBJECT_OWNERSHIP_CHANGE_GROUP),
	ADD (SERVER_OBJECT_PERMISSION_CHANGE_GROUP ),
	ADD (SERVER_PERMISSION_CHANGE_GROUP),
	ADD (SERVER_PRINCIPAL_CHANGE_GROUP ),
	ADD (SERVER_PRINCIPAL_IMPERSONATION_GROUP),
	ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP ),
	ADD (USER_CHANGE_PASSWORD_GROUP),
	ADD (USER_DEFINED_AUDIT_GROUP)
	WITH (STATE = ON)
 
	
    END


/*
This section will iterate in every database and will create the database audit specifications 

*/
 
IF (SELECT cast(left(cast(serverproperty('productversion') as varchar), 4) as decimal(5, 3))) < 11 
BEGIN 
	EXEC sp_MSforeachdb 'USE [?] 
	IF  EXISTS (SELECT 1 FROM sys.database_audit_specifications WHERE name = N''DatabaseAuditSpecification'' and is_read_only = 0 and state = 0)
	BEGIN
	 ALTER DATABASE AUDIT SPECIFICATION DatabaseAuditSpecification WITH (STATE = OFF)
	 DROP DATABASE AUDIT SPECIFICATION DatabaseAuditSpecification
	END
 
	CREATE DATABASE AUDIT SPECIFICATION [DatabaseAuditSpecification]
	FOR SERVER AUDIT [MSSQL_Server_Audit]
	ADD (APPLICATION_ROLE_CHANGE_PASSWORD_GROUP ),
	ADD (AUDIT_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (DATABASE_OWNERSHIP_CHANGE_GROUP),
	ADD (DATABASE_PERMISSION_CHANGE_GROUP ),
	ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),
	ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP ),
	ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
	ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP)
	WITH (STATE = ON)'
END
 
ELSE 
 
BEGIN
	EXEC sp_MSforeachdb 'USE [?] 
	IF  EXISTS (SELECT 1 FROM sys.database_audit_specifications WHERE name = N''DatabaseAuditSpecification'' and is_read_only = 0 and state = 0)
	BEGIN
	 ALTER DATABASE AUDIT SPECIFICATION DatabaseAuditSpecification WITH (STATE = OFF)
	 DROP DATABASE AUDIT SPECIFICATION DatabaseAuditSpecification
	END
 
	CREATE DATABASE AUDIT SPECIFICATION [DatabaseAuditSpecification]
	FOR SERVER AUDIT [MSSQL_Server_Audit]
	ADD (APPLICATION_ROLE_CHANGE_PASSWORD_GROUP ),
	ADD (AUDIT_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (DATABASE_OWNERSHIP_CHANGE_GROUP),
	ADD (DATABASE_PERMISSION_CHANGE_GROUP ),
	ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),
	ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP ),
	ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
	ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (USER_CHANGE_PASSWORD_GROUP ),
	ADD (USER_DEFINED_AUDIT_GROUP )
	WITH (STATE = ON)'
END

